---
- hosts: master[0]
  vars_files:
    - "./vars/main.yaml"
  gather_facts: false
  become: false
  tasks:
    - name: Transfer Argo CD bash file to master node
      template:
       src: templates/install.sh
       dest: /tmp/argo-cd/

    - name: Transfer Argo CD ingress to master node
      template:
       src: templates/ingress.yaml
       dest: /tmp/argo-cd/ingress.yaml

    - name: Deploy Argo on HA mode
      shell: bash -f /tmp/argo-cd/install.sh     
