apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-http-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  spec:
    ingressClassName: nginx
    tls:
      - hosts:
          - {{ ARGO_DOMAIN }}
        secretName: argocd-secret
    rules:
      - host: {{ ARGO_DOMAIN }}
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: argocd-server
                  port:
                    name: https